---
- name: Create users
  hosts: nodes
  vars_files:
    - vars/passwords

  tasks:
    - name: Create users
      user:
        name: "{{ item.name }}"
        comment: "{{ item.name }}@example.com"
        home: "/home/{{ item.name }}_dir"
        password: "{{ item.pass | password_hash('sha512') }}"
        state: present
        update_password: on_create
      loop:
        - name: Alice
          pass: "{{ Alice_secret }}"
        - name: Bob
          pass: "{{ Bob_secret }}"
        - name: Carol
          pass: "{{ Carol_secret }}"
